Azure/GPT-RAG

azure.yaml
infra/main.bicep
scripts/preDeploy.ps1
scripts/preDeploy.sh

- Add confirmation on Zero Trust about reachable resources
- persist env custom selections

Handle zero-trust deployment with confirmation

---

azure.yaml
infra/core/host/functions.bicep
infra/core/security/keyvault.bicep
infra/main.bicep

Added orchestrator post deployment script to add orchestrator function key secret to key vault after function deployment instead of doing this during service provisioning.

added orchestrator post deployment config

---

README_CUSTOM_DEPLOY.md
infra/core/search/search-services.bicep
infra/main.bicep
infra/main.parameters.json

added managed identity option for the AI search connection with data ingestion function

---

README.md
README_CUSTOM_DEPLOY.md
TROUBLESHOOTING.md
infra/main.bicep
scripts/preDeploy.sh

- Removed document chunks container (using indexProjections now).
- Increased default embeddings quota to 20 TPM.
- Improved documentation.

Using indexProjections in data ingestion

---

README.md

Publish `GPT-RAG` to azure samples browser.
@rajeshkamal5050 and @hemarina for notification.

Publish Microsoft Authored templates to azure samples browser 

---

README.md

improve zero trust installation instructions

improve zero trust installation instructions

---

README.md

According to [doc](https://review.learn.microsoft.com/en-us/help/platform/metadata-taxonomies?branch=main#product), update invalid product slug `azure-openai-service` to `azure-openai`, and remove slug `shell`.
@hemarina, @gbecerra1982  for notification.

Update invalid slugs

---

README_CUSTOM_DEPLOY.md
infra/main.bicep
scripts/postprovision.ps1
scripts/postprovision.sh
scripts/raipolicies/raipolicies.json
scripts/raipolicies/raipolicies.ps1
scripts/raipolicies/raipolicies.sh

- Added .json with content filters configuration for AOAI model
- Post provisioning .ps and .sh RAI scripts for policies setup
- Updated README Custom Deploy with AOAI content filters instructions

AOAI content filters customization

---

README_CUSTOM_DEPLOY.md
scripts/raipolicies/raipolicies.ps1

Connect-AzAccount if not signed-in. Additions to custom deployment readme: examples, microsoft doc links

RAI Content filters: Connect-AzAccount; Readme update.

---

README.md
TROUBLESHOOTING.md

Added AZ Powershell Module instructions into troubleshooting and prerequisites pages.

Documentation update: AZ Powershell Module 

---

docs/CUSTOMIZATIONS_BYOR.md

bring your own resource

---

docs/README.md

Create a subfolder `docs/README.md` to add metadata, and publish `GPT-RAG` template to azure samples browser.
@hemarina and @placerda for notification.

Publish Microsoft Authored templates to azure samples browser

---

docs/README.md

Update invalid slug `azure-ai-search` to `azure-cognitive-search`.
For more details, you can click link: https://github.com/MicrosoftDocs/samples/blob/main/Azure/gpt-rag/.samples-status.json
@placerda and @hemarina for notification.

Update invalid slug

---

README.md
docs/AUTOMATED_INSTALLATION.md

This pull request includes updates to the `README.md` and `docs/AUTOMATED_INSTALLATION.md` files to clarify the usage of the Functional and Agentic options for the Orchestrator component and to provide additional instructions for using the `-b agentic` parameter during deployment.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L30-R35): Updated the description of the Orchestrator component to distinguish between the Functional and Agentic options and added a tip about the default option.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R101-R113): Added a note to the deployment instructions to use the `-b agentic` parameter if opting for the agentic version. …

added agentic option

---

infra/core/network/vnet.bicep

Add NSG configuration to vnet.bicep
Defined Network Security Group (NSG) with necessary inbound and outbound rules
Associated NSG with the specified subnet in vnet.bicep

Add NSG configuration to vnet.bicep

---

docs/PYRIT_SECURITY_TESTING.md

This pull request adds comprehensive documentation for PyRIT security testing in the `docs/PYRIT_SECURITY_TESTING.md` file. The new documentation includes an introduction to PyRIT, its key features, and detailed descriptions of various tests used to evaluate the security of generative AI systems.

Add PyRIT Security Testing documentation

---

docs/GUIDE.md

This pull request includes multiple updates to the `docs/GUIDE.md` file, focusing on improving clarity, conciseness, and readability. The changes remove redundant information, streamline descriptions, and enhance the overall documentation quality.
* Removed redundant phrases and streamlined descriptions for better readability in various sections, including "Data Ingestion," "Deploying the Solution Accelerator," and "Configuring VNet Peering." [[1]](diffhunk://#diff-49cd8b759265ca93415f24f09658c92b903bc478b98426fa3841741f746fa772L96-R99) [[2]](diffhunk://#diff-49cd8b759265ca93415f24f09658c92b903bc478b98426fa3841741f746fa772L272-R272) [[3]](diffhunk://#diff-49cd8b759265ca93415f24f09658c92b903bc478b98426fa3841741f746fa772L424-R426)
* Simplified the explanation of the data ingestion process …

User & admin guide

---

README.md

This pull request includes a minor update to the `README.md` file to provide additional guidance for users. The change adds a link to the User & Admin Guide for comprehensive setup and usage instructions.
Documentation update:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R20-R21): Added a link to the User & Admin Guide for complete setup and usage details.

Admin guide

---

docs/SECURITY_HUB.md

This pull request includes several updates to the `docs/SECURITY_HUB.md` file to enhance the documentation related to responsible AI principles, fairness checks, and auditing capabilities. Additionally, it provides new environment variable configurations for responsible AI checks and content safety services.
* Added a new section on Responsible AI principles, including comprehensive evaluations to ensure ethical, transparent, and fair AI system development.
* Introduced a Fairness check to ensure equitable treatment of all groups by the AI system, preventing discrimination based on attributes like race, gender, age, or socioeconomic status.
* Added an Auditing feature that logs all interactions with the orchestrator to maintain transparency and accountability.
* Added environment …

Updated security hub docs

---

docs/GUIDE.md
scripts/postprovision.ps1
scripts/postprovision.sh

This pull request includes updates to documentation and scripts to ensure consistency and clarity. The most important changes include updating the note format in the documentation and correcting environment variable names in the scripts.
Issue #262
Documentation updates:
* [`docs/GUIDE.md`](diffhunk://#diff-49cd8b759265ca93415f24f09658c92b903bc478b98426fa3841741f746fa772L976-R977): Updated the note format to use a standardized Markdown note format.
Script updates:
* [`scripts/postprovision.ps1`](diffhunk://#diff-f5a00e8efcf3a8099e9f75bf6e5996d0529fdacdf24387867e4462fc8fd33ed8L25-R25): Corrected the environment variable name from `AZURE_VM_USERNAME` to `AZURE_VM_USER_NAME` to ensure consistency.
* [`scripts/postprovision.sh`](diffhunk://#diff-10742659ca6330fe03b43c59f178d0f493551912a18ac66e …

Inconsistency in Username Output between PowerShell Script and Bicep

---

docs/GUIDE.md

This pull request includes updates to the `docs/GUIDE.md` file, primarily focused on adding new resources and improving navigation within the document.
* Updated the link to the "Reference" section to correct its anchor reference.
* Added a new "Useful Links" section with several resources related to Microsoft services, including the Microsoft Customer Digital Experiences, Microsoft 365 Developer Program, and Microsoft Fabric Trial Capacity.

documentation

---

CHANGELOG.md
infra/core/security/keyvault-access.bicep
infra/core/security/keyvault.bicep
infra/main.bicep

```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
#312 
Changing the access method for the key vault can disrupt accessing secrets for the applications.
```
[x] Yes
[ ] No
```
```
[ ] Yes
[x] No
```
If this change adds a new functionality, provide a link to its documentation.
See [CONTRIBUTING.md](../CONTRIBUTING.md) for more details.

Refactor Key Vault access to use RBAC

---

infra/main.bicep

Added Search Index Data Reader permission to AI Project.
```
[x] Bugfix
[ ] Feature
[ ] Refactoring (no functional changes, no api changes)
```
```
[ ] Yes
[x] No
```
```
[ ] Yes
[x] No
```
If this change adds a new functionality, provide a link to its …

Added Search Index Data Reader role to AI Foundry

---

README.md
infra/main.bicep
infra/main.parameters.json

Add AI Foundry location selection, Service principal type fix, set batch size to 4 for container app deployment, fix the output model json in app config.
```
[ ] Bugfix
[ ] Feature
[ ] Refactoring (no functional changes, no api changes)
```
```
[ ] Yes
[ ] No
```
If the changes add new functionality, update the documentation …

ai foundry location; sp fix; batch size; endpoint fix

---

infra/install.ps1
infra/main.bicep
infra/main.parameters.json
infra/modules/standard-setup/add-account-capability-host.bicep
infra/modules/standard-setup/add-project-capability-host.bicep
infra/modules/standard-setup/ai-account-identity.bicep
infra/modules/standard-setup/ai-project-identity.bicep
infra/modules/standard-setup/cosmos-container-role-assignments.bicep
infra/modules/standard-setup/standard-dependent-resources.bicep
scripts/postProvision.ps1
scripts/postProvision.sh
scripts/register-providers.ps1

Includes all fixes for various components and automation features for ZTA support.
```
[X] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
```
[ ] Yes
[X] No
```
```
[ ] Yes
[ ] No
```
If this change adds a new functionality, …

All fixes for GPT-RAG ZTA v2

---

README.md
infra/install.ps1
infra/main.bicep

Fix the network isolation for test vm.  Branch fix.
```
[ ] Bugfix
[ ] Feature
[ ] Refactoring (no functional changes, no api changes)
```
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```
If this change adds a new functionality, provide a link to its …

add network isolation check; branch fix

---

azure.yaml
config/aifoundry/appconfig.py
config/aifoundry/keyvault.py
config/aifoundry/setup.py
config/search/search.j2
config/search/setup.py
docs/FAQS.md
infra/constants/roles.json
infra/main.bicep
infra/main.parameters.json
scripts/preDeploy.ps1

Various fixes for deployment artifacts.
```
[X] Bugfix
[ ] Feature
[ ] Refactoring (no functional changes, no api changes)
```
```
[ ] Yes
[ ] No
```
```
[ ] Yes
[ ] No
```
If this change adds a new functionality, provide a link to its documentation.

auth order; search setup fix; add nat gateway; vm msi perms

---

scripts/postProvision.ps1
scripts/preProvision.ps1

This pull request improves robustness and clarity in the provisioning scripts by enhancing environment variable checks, making setup steps conditional on required variables, and improving cleanup of temporary Python environments. It also refines the network isolation warning logic for better backward compatibility and clearer messaging.
**Environment Variable Handling & Conditional Setup**
* Added explicit checks for required environment variables (`APP_CONFIG_ENDPOINT`).
* If missing, the script now warns and skips dependent configuration steps instead of exiting early.
* Each setup section (AI Foundry, Container Apps, AI Search) only runs if the required variable is present.
* Changes applied to `scripts/postProvision.ps1` [\[1\]](diffhunk://#diff-4d7137e9b8ce383c59f16bea63c1050fe233397a …

bug-fix: ps postProvisioning

---

.github/bug_report.md
.github/config.yml
.github/feature_request.md
CHANGELOG.md
docs/pull_request_template.md
infra/main.bicep
infra/manifest.json

**Release and Deployment Updates:**
* Updated `infra/manifest.json` to reference the new release version `v2.0.5`, ensuring deployments use the latest code.
* Fixed the VM deployment script URI in `infra/main.bicep` to use the correct tag reference instead of branch, improving reliability of installations under network isolation.
* Added a changelog entry in `CHANGELOG.md` for version `v2.0.5`, documenting the fix for VM deployment errors with CustomScriptExtension in network-isolated environments.

hotfix script download
